[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'

[invariant]
seed = 0x1
runs = 1000
depth = 128
fail_on_revert = false

[rpc_endpoints]